name: Update Credly badges
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
jobs:
  update-credly-badges:
    name: Update Credly badges
    runs-on: ubuntu-24.04
    steps:
      - name: Update Credly badges
        uses: pemtajo/badge-readme@8c926df32dbf84d7c21f4359513332141942a7f0 # 3.1.0
        with:
          CREDLY_USER: davy-de-haas
          BADGE_SIZE: 200
