name: Update Credly badges
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
jobs:
  update-credly-badges:
    name: Update Credly badges
    runs-on: ubuntu-24.04
    steps:
      - name: Update Credly badges
        uses: pemtajo/badge-readme@3.2.0
        with:
          CREDLY_USER: davy-de-haas
          NUMBER_LAST_BADGES: 10
