name: Update metrics
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
jobs:
  update-metrics:
    name: Update metrics
    runs-on: ubuntu-24.04
    steps:
      - name: Embed metrics
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_traffic: yes
